COMPONENT=NdwAppC
CFLAGS += -DCC2420_DEF_RFPOWER=31
CFLAGS += -DCC2420_DEF_CHANNEL=15
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
#CFLAGS += -DREADCOMSENSOR  
CFLAGS += -I./hduco2
CFLAGS += -DENABLE_PR  
#CFLAGS += -DTOSH_DATA_LENGTH=36

CFLAGS += -I$(TOSDIR)/lib/printf

include $(MAKERULES)

